import os
import json
from collections import Counter

# === PATHS ===
script_dir = os.path.dirname(os.path.abspath(__file__))
input_folder = os.path.join(script_dir, "repaired_json")
readme_path = os.path.join(script_dir, "README.md")

# === STATS COLLECTION ===
all_mods = []
featured_mods = []
categories = Counter()
versions = Counter()

chunk_files = [f for f in os.listdir(input_folder) if f.endswith(".json")]

for chunk_file in chunk_files:
    chunk_path = os.path.join(input_folder, chunk_file)
    try:
        with open(chunk_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception:
        continue

    mods = data if isinstance(data, list) else list(data.values())
    for mod in mods:
        if not isinstance(mod, dict):
            continue

        mod_name = mod.get("name") or mod.get("fileName")
        if not mod_name:
            continue

        all_mods.append(mod_name)
        version = mod.get("version", "Unknown")
        versions[version] += 1

        cats = mod.get("categoryIds", [])
        for cat in cats:
            categories[str(cat)] += 1

        if len(featured_mods) < 10:
            featured_mods.append({
                "name": mod_name,
                "version": version,
                "url": mod.get("downloadUrl", "")
            })

# === README CONTENT ===
lines = [
    "# 🧱 Nexus 2.0 Modpack",
    "",
    "Welcome to **Nexus 2.0**, a custom-curated Minecraft experience built for immersion, performance, and expansion. This modpack is powered by a highly structured config and optimized for modular compatibility.",
    "",
    "---",
    "",
    "## 📊 Modpack Stats",
    f"- Total Mods: **{len(all_mods)}**",
    f"- Unique Versions: **{len(versions)}**",
    f"- Categories: **{len(categories)}**",
    "",
    "---",
    "",
    "## 🧩 Featured Mods",
]

for mod in featured_mods:
    line = f"- **{mod['name']}**"
    if mod['version'] and mod['version'] != "Unknown":
        line += f" (`{mod['version']}`)"
    if mod['url']:
        line += f" — [Download Link]({mod['url']})"
    lines.append(line)

lines += [
    "",
    "---",
    "",
    "## 🛠️ Installation & Usage",
    "1. Install [CurseForge Launcher](https://www.curseforge.com/downloads).",
    "2. Search for `Nexus 2.0` or import the provided ZIP into your instances.",
    "3. Allocate between **8–12GB RAM**, depending on your mod count and gameplay settings. Packs with shaders, large bases, or high-resolution textures may benefit from **10GB or more**.",
    "4. Customize configs as needed — everything is modular and documented.",
    "",
    "---",
    "",
    "## ❗ Troubleshooting",
    "- If Nexus crashes on launch, check your `forge.log` or `latest.log` for missing mods.",
    "- Use `repair_chunk.py` and `generate_dashboard.py` to clean and inspect config files.",
    "- For support, open a thread in our Discord or CurseForge Comments section.",
    "",
    "---",
    "",
    "## 🌐 External Links",
    "- [📁 CurseForge Page](https://www.curseforge.com/minecraft/modpacks/nexus-2-0)",
    "- [💬 Discord Community](https://discord.gg/yourserverlink)",
    "- [🛠 GitHub Toolkit](https://github.com/yourrepo/nexus-tools)",
    "",
    "---",
    "",
    "_README generated by Copilot Modpack Tools — curated by Matt_"
]

# === WRITE FILE ===
with open(readme_path, 'w', encoding='utf-8') as f:
    f.write("\n".join(lines))

print(f"✅ README.md saved to: {readme_path}")